### PR TITLE
Fixed counting issue

### PR DESCRIPTION
**Pull request by jpike88**

### CODE REVIEW

**Comment by jpike88** [comment]
I fixed it this time.

Two issues: 

- [ ] Line 12 of test.js contains the key of your app's translation spreadsheet. You might want to get rid of that.
- [ ] In your testing spreadsheet (key '1cKTLZCglRJkJR_7NGL6vPn1MHdadcLPUOMYjqVKFlB4'), you should find that without my bug fix, if you put a value down at row 1000 (or the last row), you won't get that value. It's because rowCount is not taking firstRow into account. If you're offsetting firstRow, you need to offset the rowCount as well to ensure you aren't undercounting the available rows.

**Comment by mikhail-angelov** [comment]
ok, fix is better and test works
now I understand the issue - last couple rows are not processed


but instead of this fix
`rowCount = rowCount + firstRow + 1;`

it's better to adjust this cycle condition

`for (var i = firstRow + 1; i <= rowCount; i++) {`

**Comment by jpike88** [comment]
done

**Comment by mikhail-angelov** [comment]
cool
released gulp-translations-from-spreadsheet@1.3.1

**Pull request merged**
